### PR TITLE
Add description of Technical Review Committee

### PR DESCRIPTION
**Pull request by zimeon**
Adds description of TRC in /community/trc/

### CODE REVIEW

**Comment by glenrobson** [comment]
Its now live at:

https://preview.iiif.io/root/add-trc/community/trc/index.html

**Comment by glenrobson** [comment]
Branch aviliable for testing at https://preview.iiif.io/root/add-trc

**Comment by zimeon** [comment]
Have got @glenrobson's link fix via rebase to master

**Comment by zimeon** [comment]
https://preview.iiif.io/root/add-trc/community/trc/ looks good, where should it be linked to from?

**Comment by glenrobson** [comment]
Great thanks Im going to merge so its ready for the community call.

**Pull request merged**
