### PR TITLE
Fix typos on 2019-07-01-newsletter.md

### PR DESCRIPTION
**Pull request by regisrob**
Just fixed a few typos: missing spaces in the text body and a missing bullet in the list of contributions

### CODE REVIEW

**Comment by julsraemy** [comment]
See https://github.com/IIIF/website/pull/264 :)

**Comment by hadro** [comment]
@julsraemy, are all these covered by #264? If so I'll close this up but let me know

**Comment by julsraemy** [comment]
@hadro almost! the last line (Régis' affiliations) is not.

**Comment by julsraemy** [comment]
@regisrob can you edit your PR (only line 243 needs to be changed) before @hadro or @glenrobson can merge it?

**Comment by regisrob** [comment]
@julsraemy done

**Comment by hadro** [comment]
Thanks, both!

**Pull request merged**
