### PR TITLE
Editorial committee details

### LINKED ISSUE #159: Move editorial committee membership from /api/ to /community/, update re TRC
As part of https://github.com/IIIF/api/issues/1637 there should be:
  * `/community/editors/` -- editorial committee membership and role
  * `/community/policy/editorial/` -- editorial committee process
and then we remove the existing https://iiif.io/api/annex/notes/editors/ and fix links in /api/

### PR DESCRIPTION
**Pull request by zimeon**
Closes #159

### CODE REVIEW

**Comment by glenrobson** [comment]
Branch aviliable for testing at https://preview.iiif.io/root/issue-159

**Comment by glenrobson** [comment]
Is this ready to go?

**Comment by azaroth42** [comment]
@glenrobson Go ahead and merge :)

**Comment by glenrobson** [comment]
Thanks all.

**Pull request merged**
