### PR TITLE
Adding upcoming group calls to front page. 

### PR DESCRIPTION
**Pull request by glenrobson**

### CODE REVIEW

**Comment by glenrobson** [comment]
This version currently does:

* Pull in the next 5 upcoming IIIF calls, either TSG or Community Group or Community Call (MVP)
* Don’t pull in anything that’s not one of those (MVP)
* Find way to pull in language about recurring nature of calls (e.g. “meets every two weeks” or “once a month”)
* Also a function to display “This groups next call is on Month Day, at Time:Time” for each community group/TSG
* Link from Homepage to group page with above info. 

but needs to take list of events and their information from a config file. Also front page events and community upcoming call needs styling.

**Comment by glenrobson** [comment]
Moved to storing the json rather than dynamically getting it from google. The time for the previous version was used initiating the google javascript and downloading the calendar information. There is now an example calendar.json in the source directory with the required information in it. This has speed it up but there is still a slight delay as it loads. For the live version this file would have to be regularly updated through a lambda function running once or twice a day. It would have to be stored on the live site s3 bucket and all preview versions of the website would have to be hardcoded to go to iiif.io.

**Comment by glenrobson** [comment]
Also repeating event information isn't in the google json. It may be best to drive this from the data file mentioned above with the following information:
 * Short group name
 * Name in google calendar
 * Meeting frequency
 * Link to group page.

This data file could also be used to generate: https://preview.iiif.io/root/group_calls/community/groups/

**Comment by hadro** [comment]
Thanks, Glen. Yes, I think the meeting frequency and other data are fine to pull from a config file.
It's definitely faster, so hopefully that does it.
Thanks for looking into it.
Are you ok with me merging into new_theme now, or are there any other changes you want to add?

**Pull request merged**
