### PR TITLE
First draft of virtual event page

### PR DESCRIPTION
**Pull request by hadro**

### CODE REVIEW

**Comment by glenrobson** [comment]
Branch available for testing at https://preview.iiif.io/root/virtual_event

**Comment by hadro** [comment]
- [ ] Add newsletter signup to this page
- [ ] Add intro copy
- [ ] Comment about where to go to see recordings afterwards

**Comment by hadro** [comment]
Functionality that perhaps @glenrobson can help with: 
- [ ] a pull down menu that would show each event time in a localized time zone of the users choice
- [ ] A "call to action" button next to each session that opens the registration form for that particular session

**Comment by glenrobson** [comment]
I've added the following section for the workshop:

https://preview.iiif.io/root/virtual_event/event/2020/online/#iiif-hands-on-workshop

When we have more of a plan I think it should be a separate page which this intro would link to.

**Comment by glenrobson** [comment]
For discussion but it looks like we can make the embedded calendar show the events in the users timezone rather than hard coding it to New York:

https://stackoverflow.com/questions/31821974/support-user-time-zone-in-embedded-google-calendar/42461423

**Comment by glenrobson** [comment]
Just thinking we need a logo or image for the conference....

**Comment by hadro** [comment]
I've added some basic functionality that *should* show the Google Calendar in the person's local time zone, and should also display event times translated to their time zone as well -- but definitely needs testing!

**Pull request merged**
