### PR TITLE
Add draft showcase schedule

### PR DESCRIPTION
**Pull request by glenrobson**
Creating a pull request for Josh's work so we can look at the preview link.

### CODE REVIEW

**Comment by glenrobson** [comment]
Branch aviliable for testing at https://preview.iiif.io/root/ann_arbor

**Comment by glenrobson** [comment]
Just noting some changes that need to be made:

https://preview.iiif.io/root/ann_arbor/event/2019/ann_arbor/showcase/

 * Location says Alte Mensa
 * Could we add more details to the reception?

**Comment by hadro** [comment]
@glenrobson let me know if this looks good to merge, or go for it if you think it's ok

**Comment by glenrobson** [comment]
Thanks Merged

**Pull request merged**
