### PR TITLE
Address tracking of good standing per issue-123 discussion

### LINKED ISSUE #123: How will TRC member participation be tracked in order to establish good standing?
The proposed TRC process relies upon active engagement of participants and a notion of participation-based good standing in order to be able to vote. We need a transparent and lightweight process for tracking participation and good standing status in order to implement this.

### PR DESCRIPTION
**Pull request by zimeon**
Closes #123

### CODE REVIEW

**Comment by zimeon** [comment]
Travis issue is just external link

**Comment by glenrobson** [comment]
Branch aviliable for testing at https://preview.iiif.io/root/issue-123

**Comment by zimeon** [comment]
@glenrobson ... if we want to do this, how about the following?

> ... If a consortium or community member of the TRC does not participate over the timeframe of three consecutive meetings **(without prior apologies for a prolonged absence)**, then they are not in "good standing" and their vote will not count on issues until they have participated for three consecutive meetings. ...

**Comment by glenrobson** [comment]
That would be good for me.

**Comment by mattmcgrattan** [comment]
+1

**Comment by zimeon** [comment]
Merging into `add-trc` branch as agreed but editing group

**Pull request merged**
